# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-cl" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "9bac8fc8c8a4c20dce10f1fbdf6fb35eaf9ccd4398b3b083ca5602eb1e0ec500"
      url "https://github.com/sascha-andres/git-cl/releases/download/v#{version}/git-cl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a5c493e228ec2341f81a9a1c5a3a220681e0b1b02a6d6524cd8e55c385f75174"
      url "https://github.com/sascha-andres/git-cl/releases/download/v#{version}/git-cl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "142949939dc41ba99ef18a9bd435f8042eef507158e40fdbadaebd13ce04ba2e"
      url "https://github.com/sascha-andres/git-cl/releases/download/v#{version}/git-cl_linux_arm64.tar.gz"
    end
  end

  name "git-cl"
  desc "Generates a changelog from a list of conventional commit messages"
  homepage "https://github.com/sascha-andres/git-cl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-cl"

  postflight do
    system_command "codesign", args: ["--force", "-s", "-", "#{staged_path}/git-cl"]
  end

  # No zap stanza required

end
