# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-c" do
  version "0.2.6"

  on_macos do
    on_arm do
      sha256 "b656602f9536f46b8b2fb25004ac9b3282109a59ed4a492a38537bac20046007"
      url "https://github.com/sascha-andres/git-c/releases/download/v#{version}/git-c_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "477b232b1d78217df8609bc5aae2a42cf1081e4f82fa871530587d229a56132c"
      url "https://github.com/sascha-andres/git-c/releases/download/v#{version}/git-c_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc5d9112a216c74faf6becf0c1e87864f3e49e430f8793c4e35c10b972cc58b5"
      url "https://github.com/sascha-andres/git-c/releases/download/v#{version}/git-c_linux_arm64.tar.gz"
    end
  end

  name "git-c"
  desc "Loosely inspired by cz-cli, helps write conventional commit messages"
  homepage "https://github.com/sascha-andres/git-c"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-c"

  postflight do
    system "codesign", "--force", "-s", "-", "#{bin}/git-c"
  end

  # No zap stanza required

end
