# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-cl" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "a7c90b555db92e81d66a15e3dfd9bfd7e24ad6d6f69127befb8778b7eb95ec41"
      url "https://github.com/sascha-andres/git-cl/releases/download/v#{version}/git-cl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a1f3e46ed2732aab05bcaa036c1a24d30f3ee96043bfb29d24a95b1dd6f6b2b"
      url "https://github.com/sascha-andres/git-cl/releases/download/v#{version}/git-cl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6d22be5de8d395b8d983c20a93ea1fae18765613e8f9df6c38cee10c3a5cee4"
      url "https://github.com/sascha-andres/git-cl/releases/download/v#{version}/git-cl_linux_arm64.tar.gz"
    end
  end

  name "git-cl"
  desc "Generates a changelog from a list of conventional commit messages"
  homepage "https://github.com/sascha-andres/git-cl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-cl"

  postflight do
    system "codesign", "--force", "-s", "-", "#{bin}/git-cl"
  end

  # No zap stanza required

end
