# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-c" do
  version "0.2.5"

  on_macos do
    on_arm do
      sha256 "e637db68c39ee918352714fca3f464758ad1a72cbc588ba5cdb68a234eedbac6"
      url "https://github.com/sascha-andres/git-c/releases/download/v#{version}/git-c_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da4712fcd4feaba1e0ee73e6c095b8a3621810ba1dfd24bb0e163fcda74ca244"
      url "https://github.com/sascha-andres/git-c/releases/download/v#{version}/git-c_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59416c79d293116e758b3a0f89b87d810bcbe3102e2454315882b74f9bb34de1"
      url "https://github.com/sascha-andres/git-c/releases/download/v#{version}/git-c_linux_arm64.tar.gz"
    end
  end

  name "git-c"
  desc "Loosely inspired by cz-cli, helps write conventional commit messages"
  homepage "https://github.com/sascha-andres/git-c"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-c"

  # No zap stanza required

end
