# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-c" do
  version "0.2.5"

  on_macos do
    on_arm do
      sha256 "cef564babe8e75f5791b30c5c67684dd4b77ef7caa96f474fc9b0d71a9659fef"
      url "https://github.com/sascha-andres/git-c/releases/download/v#{version}/git-c_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6ab3d0245f7d0e1a2d09f4563d45a14e1c6fd64395b1ba777628b91c60b5f78"
      url "https://github.com/sascha-andres/git-c/releases/download/v#{version}/git-c_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7c6e285db48e75f8d983e90d68bb5b1f5c6d87a97139436615d403c509ce8e1"
      url "https://github.com/sascha-andres/git-c/releases/download/v#{version}/git-c_linux_arm64.tar.gz"
    end
  end

  name "git-c"
  desc "Loosely inspired by cz-cli, helps write conventional commit messages"
  homepage "https://github.com/sascha-andres/git-c"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-c"

  # No zap stanza required

end
