# This file was generated by GoReleaser. DO NOT EDIT.
cask "godl" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "e2ba8cde5659a4715a0c9886f00852d6a2d13258fc0636c938e1c03dd9e87105"
      url "https://github.com/sascha-andres/godl/releases/download/v#{version}/godl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4bfce7a4bb5c722e3f52e3d49a3667c55c438ea8c9260b9888557937ac1aed6"
      url "https://github.com/sascha-andres/godl/releases/download/v#{version}/godl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad5c805d7ab67a53cbd7d1a03da1cae28d8719b3b9b3cfda0ce482e770afef2d"
      url "https://github.com/sascha-andres/godl/releases/download/v#{version}/godl_linux_arm64.tar.gz"
    end
  end

  name "godl"
  desc "Similar to ansible-role-golang but implemented as a single binary"
  homepage "https://github.com/sascha-andres/godl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "godl"

  # No zap stanza required

end
