# This file was generated by GoReleaser. DO NOT EDIT.
cask "godl" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "14bec2ff549aa42f7d77bcb218ce75fe97bab86413ef18c39b127fdd97e287a3"
      url "https://github.com/sascha-andres/godl/releases/download/v#{version}/godl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58b519060efd17667abdb9586713c4575ad71e54dd9d4669034908ceae8395d1"
      url "https://github.com/sascha-andres/godl/releases/download/v#{version}/godl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c45a79008f17db73fc11d387a43b75763556a260a5995952a678f3baadc5ce1e"
      url "https://github.com/sascha-andres/godl/releases/download/v#{version}/godl_linux_arm64.tar.gz"
    end
  end

  name "godl"
  desc "Similar to ansible-role-golang but implemented as a single binary"
  homepage "https://github.com/sascha-andres/godl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "godl"

  postflight do
    system "codesign", "--force", "-s", "-", "#{bin}/godl"
  end

  # No zap stanza required

end
