# This file was generated by GoReleaser. DO NOT EDIT.
cask "godl" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "b902f247fb71580abec67e393826f90775538e5e78532e822fbe8196402f8a79"
      url "https://github.com/sascha-andres/godl/releases/download/v#{version}/godl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4590318b3339f4f3b9935d93ab0e84c36d3edc0ff2030c2df87f7bfa720d6336"
      url "https://github.com/sascha-andres/godl/releases/download/v#{version}/godl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e7dfaa3591ec4df6167c69ef24ae236bc81a784bbaeb0d6ab887f560e346205"
      url "https://github.com/sascha-andres/godl/releases/download/v#{version}/godl_linux_arm64.tar.gz"
    end
  end

  name "godl"
  desc "Similar to ansible-role-golang but implemented as a single binary"
  homepage "https://github.com/sascha-andres/godl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "godl"

  postflight do
    system_command "codesign", args: ["--force", "-s", "-", "#{staged_path}/godl"]
  end

  # No zap stanza required

end
