# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godl < Formula
  desc "Similar to ansible-role-golang but implemented as a single binary"
  homepage "https://github.com/sascha-andres/godl"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sascha-andres/godl/releases/download/v0.2.0/godl_darwin_arm64.tar.gz"
      sha256 "cb0bdcc42d4269f9587d27a8b98e67917162f50e99c8613221762350f613685b"

      define_method(:install) do
        bin.install "godl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sascha-andres/godl/releases/download/v0.2.0/godl_linux_amd64.tar.gz"
      sha256 "5214027422c5f5f2ee854ee308bad3218a5bbe911334c91d4db3e1a0a0c330ab"
      define_method(:install) do
        bin.install "godl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sascha-andres/godl/releases/download/v0.2.0/godl_linux_arm64.tar.gz"
      sha256 "4671c15cbbc59482011235cb53871984764f41616e61d8c26e06df6f4ef3e564"
      define_method(:install) do
        bin.install "godl"
      end
    end
  end

  test do
    system "#{bin}/godl", "-tool-version"
  end
end
