# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ObsidianUtils < Formula
  desc "Collection of CLI utilities for managing an Obsidian vault"
  homepage "https://github.com/sascha-andres/obsidian-utils"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sascha-andres/obsidian-utils/releases/download/v0.4.0/obsidian-utils_darwin_amd64.tar.gz"
      sha256 "34e504d84e2ee68d104a8dd7477b5481abe5515907ac622f5ce4ddfe20e75bb4"

      define_method(:install) do
        bin.install "am"
        bin.install "backfill"
        bin.install "daily"
        bin.install "ggl"
        bin.install "ical"
        bin.install "jrnl"
        bin.install "obs-fm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sascha-andres/obsidian-utils/releases/download/v0.4.0/obsidian-utils_darwin_arm64.tar.gz"
      sha256 "c1eb3b80983f69290736837a8fc097cc626ed289ca1527d32e5d770153abd7a8"

      define_method(:install) do
        bin.install "am"
        bin.install "backfill"
        bin.install "daily"
        bin.install "ggl"
        bin.install "ical"
        bin.install "jrnl"
        bin.install "obs-fm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sascha-andres/obsidian-utils/releases/download/v0.4.0/obsidian-utils_linux_amd64.tar.gz"
      sha256 "aeca6908563e0cba80923ab8ec4bd36179c78c398c1bd10e905b1e3de7122baa"
      define_method(:install) do
        bin.install "am"
        bin.install "backfill"
        bin.install "daily"
        bin.install "ggl"
        bin.install "ical"
        bin.install "jrnl"
        bin.install "obs-fm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sascha-andres/obsidian-utils/releases/download/v0.4.0/obsidian-utils_linux_arm64.tar.gz"
      sha256 "c5487070f3d51e27e4513e99d475da0ce2138af7eaeb16d6b3ade77e68859314"
      define_method(:install) do
        bin.install "am"
        bin.install "backfill"
        bin.install "daily"
        bin.install "ggl"
        bin.install "ical"
        bin.install "jrnl"
        bin.install "obs-fm"
      end
    end
  end

  test do
    %w[am backfill daily ggl ical jrnl obs-fm].each do |b|
      assert_predicate bin/b, :exist?
    end
  end
end
